### ISSUE TITLE
Update branch failure

### ISSUE THREAD

**Issue by sileht** [Mergifyio/mergify-engine#334]
```
mergify-logs/worker-beat.out-2019-01-10 23:56:45,688 [22384] INFO     [b7eea676-d50b-4241-8a88-647cbaf49584] mergify_engine.utils: calling: merge --quiet upstream/master -m Merge branch 'master' into 'XXXXXXXXXX'
mergify-logs/worker-beat.out-2019-01-10 23:56:45,970 [22384] INFO     [b7eea676-d50b-4241-8a88-647cbaf49584] mergify_engine.utils: calling: push --quiet origin XXXXXXXXXXXX
mergify-logs/worker-beat.out-To https://github.com/XXXXXXXX/XXXXXXXX
mergify-logs/worker-beat.out- ! [rejected]        XXXXXXX -> XXXXXXXXX (fetch first)
mergify-logs/worker-beat.out-error: failed to push some refs to 'https://github.com/XXXXXXX/XXXXXXXx'
mergify-logs/worker-beat.out-hint: Updates were rejected because the remote contains work that you do
mergify-logs/worker-beat.out-hint: not have locally. This is usually caused by another repository pushing
mergify-logs/worker-beat.out-hint: to the same ref. You may want to first integrate the remote changes
mergify-logs/worker-beat.out-hint: (e.g., 'git pull ...') before pushing again.
mergify-logs/worker-beat.out-hint: See the 'Note about fast-forwards' in 'git push --help' for details.
mergify-logs/worker-beat.out:2019-01-10 23:56:47,429 [22384] ERROR    [b7eea676-d50b-4241-8a88-647cbaf49584] mergify_engine.branch_updater [pull_request: XXXXXXX/XXXXXXX/pull/YYY@master s:behind]: update branch fail
mergify-logs/worker-beat.out-Traceback (most recent call last):
mergify-logs/worker-beat.out-  File "/data/web_www/gh.mergify.io/src/mergify_engine/branch_updater.py", line 70, in update
mergify-logs/worker-beat.out-    git("push", "--quiet", "origin", head_branch)
mergify-logs/worker-beat.out-  File "src/mergify_engine/utils.py", line 221, in __call__
mergify-logs/worker-beat.out-    return subprocess.check_output(["git"] + list(args), **kwargs)
mergify-logs/worker-beat.out-  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
mergify-logs/worker-beat.out-    **kwargs).stdout
mergify-logs/worker-beat.out-  File "/usr/lib/python3.5/subprocess.py", line 398, in run
mergify-logs/worker-beat.out-    output=stdout, stderr=stderr)
mergify-logs/worker-beat.out-subprocess.CalledProcessError: Command '['git', 'push', '--quiet', 'origin', 'SISU-800']' returned non-zero exit status 1

```

This occurs when we handle two events about the same PR in // that want to update the branch. We have code that check if PR have been merged in the meantime, we should also add code to check if PR have been updated in the meantime (by user or mergify): https://github.com/Mergifyio/mergify-engine/blob/master/mergify_engine/actions/merge.py#L253-L257

**Comment by sileht** [comment]
Cannot occurs anymore updates are serialized.
